In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("bank+marketing/bank/bank-full.csv", sep = ';', engine = 'python')

In [3]:
df.head()

age           job  marital  education default  balance housing loan  \
0   58    management  married   tertiary      no     2143     yes   no   
1   44    technician   single  secondary      no       29     yes   no   
2   33  entrepreneur  married  secondary      no        2     yes  yes   
3   47   blue-collar  married    unknown      no     1506     yes   no   
4   33       unknown   single    unknown      no        1      no   no   

   contact  day month  duration  campaign  pdays  previous poutcome   y  
0  unknown    5   may       261         1     -1         0  unknown  no  
1  unknown    5   may       151         1     -1         0  unknown  no  
2  unknown    5   may        76         1     -1         0  unknown  no  
3  unknown    5   may        92         1     -1         0  unknown  no  
4  unknown    5   may       198         1     -1         0  unknown  no

In [4]:
len(df)

45211

In [5]:
df.y.value_counts()

y
no     39922
yes     5289
Name: count, dtype: int64

In [6]:
df.y.value_counts(normalize=True)

y
no     0.883015
yes    0.116985
Name: proportion, dtype: float64

In [7]:
df = df[["age", "job", "marital", "education", "balance", "housing", "contact", "day", 
         "month", "duration", "campaign", "pdays", "previous", "poutcome", "y"]]

In [8]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [9]:
# Question 1
# What is the most frequent observation (mode) for the column education?
df.education.value_counts()

education
secondary    23202
tertiary     13301
primary       6851
unknown       1857
Name: count, dtype: int64

In [10]:
df.education.mode()

0    secondary
Name: education, dtype: object

# Question 2

Create the correlation matrix for the numerical features of your dataset. In a correlation matrix, you compute the correlation coefficient between every pair of features.

What are the two features that have the biggest correlation?
* age and balance
* day and campaign
* day and pdays
* pdays and previous

In [11]:
df.dtypes

age           int64
job          object
marital      object
education    object
balance       int64
housing      object
contact      object
day           int64
month        object
duration      int64
campaign      int64
pdays         int64
previous      int64
poutcome     object
y            object
dtype: object

In [12]:
df.columns = df.columns.str.lower().str.replace(' ', '_')

categorical = list(df.dtypes[df.dtypes == 'object'].index)

for c in categorical:
    df[c] = df[c].str.lower().str.replace(' ', '_')

In [13]:
categorical

['job', 'marital', 'education', 'housing', 'contact', 'month', 'poutcome', 'y']

In [14]:
categorical.remove("y")

In [15]:
numerical = list(df.dtypes[df.dtypes == 'int'].index)

In [16]:
numerical

['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [17]:
corr_matrix = round(df[numerical].corr(),2)

print(corr_matrix)

           age  balance   day  duration  campaign  pdays  previous
age       1.00     0.10 -0.01     -0.00      0.00  -0.02      0.00
balance   0.10     1.00  0.00      0.02     -0.01   0.00      0.02
day      -0.01     0.00  1.00     -0.03      0.16  -0.09     -0.05
duration -0.00     0.02 -0.03      1.00     -0.08  -0.00      0.00
campaign  0.00    -0.01  0.16     -0.08      1.00  -0.09     -0.03
pdays    -0.02     0.00 -0.09     -0.00     -0.09   1.00      0.45
previous  0.00     0.02 -0.05      0.00     -0.03   0.45      1.00


In [26]:
corr_matrix.abs()

age  balance   day  duration  campaign  pdays  previous
age       1.00     0.10  0.01      0.00      0.00   0.02      0.00
balance   0.10     1.00  0.00      0.02      0.01   0.00      0.02
day       0.01     0.00  1.00      0.03      0.16   0.09      0.05
duration  0.00     0.02  0.03      1.00      0.08   0.00      0.00
campaign  0.00     0.01  0.16      0.08      1.00   0.09      0.03
pdays     0.02     0.00  0.09      0.00      0.09   1.00      0.45
previous  0.00     0.02  0.05      0.00      0.03   0.45      1.00

In [28]:
corr_matrix.abs().unstack().sort_values(kind="quicksort")

duration  age         0.00
pdays     duration    0.00
          balance     0.00
campaign  age         0.00
duration  previous    0.00
          pdays       0.00
previous  duration    0.00
day       balance     0.00
balance   pdays       0.00
previous  age         0.00
age       previous    0.00
          duration    0.00
          campaign    0.00
balance   day         0.00
          campaign    0.01
age       day         0.01
day       age         0.01
campaign  balance     0.01
balance   duration    0.02
previous  balance     0.02
pdays     age         0.02
duration  balance     0.02
age       pdays       0.02
balance   previous    0.02
duration  day         0.03
previous  campaign    0.03
campaign  previous    0.03
day       duration    0.03
previous  day         0.05
day       previous    0.05
campaign  duration    0.08
duration  campaign    0.08
day       pdays       0.09
campaign  pdays       0.09
pdays     day         0.09
          campaign    0.09
balance   age         0.10
a

In [29]:
corr = df[numerical].corr()
corr.style.background_gradient(cmap='coolwarm')
# 'RdBu_r', 'BrBG_r', & PuOr_r are other good diverging colormaps

Answer: Two features that have the biggest correlation are *previous and pdays*

In [30]:
# Target encoding
df.y = (df.y == "yes").astype(int)

In [31]:
df.head()

age           job  marital  education  balance housing  contact  day month  \
0   58    management  married   tertiary     2143     yes  unknown    5   may   
1   44    technician   single  secondary       29     yes  unknown    5   may   
2   33  entrepreneur  married  secondary        2     yes  unknown    5   may   
3   47   blue-collar  married    unknown     1506     yes  unknown    5   may   
4   33       unknown   single    unknown        1      no  unknown    5   may   

   duration  campaign  pdays  previous poutcome  y  
0       261         1     -1         0  unknown  0  
1       151         1     -1         0  unknown  0  
2        76         1     -1         0  unknown  0  
3        92         1     -1         0  unknown  0  
4       198         1     -1         0  unknown  0

In [32]:
df.y.value_counts()

y
0    39922
1     5289
Name: count, dtype: int64

Split the data
* Split your data in train/val/test sets with 60%/20%/20% distribution.
* Use Scikit-Learn for that (the train_test_split function) and set the seed to 42.
* Make sure that the target value y is not in your dataframe.

In [33]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=42)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state=42)

In [34]:
len(df_train), len(df_val), len(df_test)

(27126, 9042, 9043)

In [35]:
df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [36]:
y_train = df_train.y.values
y_val = df_val.y.values
y_test = df_test.y.values

In [37]:
del df_train['y']
del df_val['y']
del df_test['y']

In [38]:
df_train.head()

age            job  marital  education  balance housing   contact  day  \
0   32     technician   single   tertiary     1100     yes  cellular   11   
1   38   entrepreneur  married  secondary        0     yes  cellular   17   
2   49    blue-collar  married  secondary     3309     yes  cellular   15   
3   37      housemaid  married    primary     2410      no  cellular    4   
4   31  self-employed  married   tertiary     3220      no  cellular   26   

  month  duration  campaign  pdays  previous poutcome  
0   aug        67         1     -1         0  unknown  
1   nov       258         1     -1         0  unknown  
2   may       349         2     -1         0  unknown  
3   aug       315         1     -1         0  unknown  
4   aug        74         4     -1         0  unknown

In [39]:
np.unique(y_train, return_counts=True)

(array([0, 1]), array([23998,  3128]))

# Question 3

Calculate the mutual information score between y and other categorical variables in the dataset. Use the training set only.

Round the scores to 2 decimals using round(score, 2).
Which of these variables has the biggest mutual information score?
* contact
* education
* housing
* poutcome

In [40]:
df_full_train[categorical].nunique()

job          12
marital       3
education     4
housing       2
contact       3
month        12
poutcome      4
dtype: int64

Mutual information - concept from information theory, it tells us how much we can learn about one variable if we know the value of another

https://en.wikipedia.org/wiki/Mutual_information

In [41]:
from sklearn.metrics import mutual_info_score

def mutual_info_y_score(series):
    return mutual_info_score(series, df_full_train.y)

In [42]:
mi = df_full_train[categorical].apply(mutual_info_y_score)
round(mi.sort_values(ascending=False), 2)

poutcome     0.03
month        0.02
contact      0.01
housing      0.01
job          0.01
education    0.00
marital      0.00
dtype: float64

Answer: *poutcome* the biggest mutual information score

# Question 4
* Now let's train a logistic regression.
* Remember that we have several categorical variables in the dataset. Include them using one-hot encoding.
* Fit the model on the training dataset.
  - To make sure the results are reproducible across different versions of Scikit-Learn, fit the model with these parameters:
  - model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
* Calculate the accuracy on the validation dataset and round it to 2 decimal digits.

What accuracy did you get?

In [43]:
from sklearn.feature_extraction import DictVectorizer

In [44]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)

In [45]:
dv

DictVectorizer(sparse=False)

In [46]:
print(list(X_train[0]))

[32.0, 1100.0, 1.0, 1.0, 0.0, 0.0, 11.0, 67.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 1.0, 0.0]


In [47]:
df_train[:1]

age         job marital education  balance housing   contact  day month  \
0   32  technician  single  tertiary     1100     yes  cellular   11   aug   

   duration  campaign  pdays  previous poutcome  
0        67         1     -1         0  unknown

In [48]:
from sklearn.linear_model import LogisticRegression

In [49]:
model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)

In [50]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, random_state=42, solver='liblinear')

In [51]:
model.intercept_[0]

-0.9776792931251067

In [52]:
model.coef_[0].round(3)

array([ 1.000e-03,  0.000e+00, -7.800e-02,  2.540e-01,  8.100e-02,
       -1.313e+00,  9.000e-03,  4.000e-03, -4.440e-01, -2.510e-01,
       -5.500e-02, -2.280e-01, -1.430e-01, -8.350e-01,  9.500e-02,
       -2.420e-01, -2.640e-01, -3.310e-01, -8.100e-02,  2.710e-01,
       -2.930e-01, -1.310e-01,  2.870e-01, -1.480e-01,  3.200e-02,
       -1.720e-01, -3.500e-01, -4.760e-01, -1.510e-01, -7.000e-03,
       -7.130e-01,  3.880e-01, -3.280e-01, -1.159e+00, -1.043e+00,
        3.010e-01,  1.450e+00, -5.010e-01, -9.450e-01,  7.850e-01,
        7.950e-01, -1.000e-03, -7.910e-01, -5.870e-01,  1.504e+00,
       -1.104e+00,  6.000e-03])

In [53]:
y_pred = model.predict_proba(X_val) #[:, 1]

In [54]:
y_pred

array([[0.9876019 , 0.0123981 ],
       [0.98988303, 0.01011697],
       [0.84530916, 0.15469084],
       ...,
       [0.94407911, 0.05592089],
       [0.99094851, 0.00905149],
       [0.71549047, 0.28450953]])

In [55]:
y_pred = model.predict_proba(X_val)[:, 1]

In [56]:
y_pred

array([0.0123981 , 0.01011697, 0.15469084, ..., 0.05592089, 0.00905149,
       0.28450953])

In [57]:
y_decision = (y_pred >= 0.5)

In [58]:
y_decision

array([False, False, False, ..., False, False, False])

In [59]:
y_val

array([0, 0, 1, ..., 0, 0, 1])

In [60]:
(y_val == y_decision).mean()

0.9007962840079629

In [61]:
df_pred = pd.DataFrame()
df_pred['probability'] = y_pred
df_pred['prediction'] = y_decision.astype(int)
df_pred['actual'] = y_val

In [62]:
df_pred['correct'] = df_pred.prediction == df_pred.actual

In [63]:
df_pred

probability  prediction  actual  correct
0        0.012398           0       0     True
1        0.010117           0       0     True
2        0.154691           0       1    False
3        0.226219           0       0     True
4        0.443337           0       1    False
...           ...         ...     ...      ...
9037     0.022102           0       0     True
9038     0.265153           0       1    False
9039     0.055921           0       0     True
9040     0.009051           0       0     True
9041     0.284510           0       1    False

[9042 rows x 4 columns]

In [64]:
df_pred.correct.mean()

0.9007962840079629

In [65]:
acc_score_all = df_pred.correct.mean()

In [66]:
# the answer is
print ("The answer is", round(df_pred.correct.mean(), 2))

The answer is 0.9


# Question 5
* Let's find the least useful feature using the feature elimination technique.
* Train a model with all these features (using the same parameters as in Q4).
* Now exclude each feature from this set and train a model without it. Record the accuracy for each model.
* For each feature, calculate the difference between the original accuracy and the accuracy without the feature.

Which of following feature has the smallest difference?
* age, balance, marital, previous?

Note: The difference doesn't have to be positive.

In [67]:
categorical

['job', 'marital', 'education', 'housing', 'contact', 'month', 'poutcome']

In [68]:
numerical

['age', 'balance', 'day', 'duration', 'campaign', 'pdays', 'previous']

In [69]:
test_features = ["age", "balance", "marital", "previous"]

In [72]:
ac_difference = []
for elem in test_features:
    features = categorical + numerical
    features.remove(elem)
    
    #dv = DictVectorizer(sparse=False)
    
    train_dict = df_train[features].to_dict(orient='records')
    X_train = dv.fit_transform(train_dict)
    
    val_dict = df_val[features].to_dict(orient='records')
    X_val = dv.transform(val_dict)

    #model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)
    
    y_pred = model.predict_proba(X_val)[:, 1]
    y_decision = (y_pred >= 0.5)
    accuracy_score = (y_val == y_decision).mean()
    ac_difference.append(acc_score_all-accuracy_score)
    print ("Accuracy score without feature {} = {} \nThe difference between the original accuracy and the accuracy without {} = {}".format(elem, accuracy_score, elem, acc_score_all-accuracy_score))

Accuracy score without feature age = 0.9010174740101747 
The difference between the original accuracy and the accuracy without age = -0.00022119000221187957
Accuracy score without feature balance = 0.9007962840079629 
The difference between the original accuracy and the accuracy without balance = 0.0
Accuracy score without feature marital = 0.9014598540145985 
The difference between the original accuracy and the accuracy without marital = -0.0006635700066356387
Accuracy score without feature previous = 0.9014598540145985 
The difference between the original accuracy and the accuracy without previous = -0.0006635700066356387


In [73]:
ac_difference

[-0.00022119000221187957, 0.0, -0.0006635700066356387, -0.0006635700066356387]

In [74]:
res = [abs(elem) for elem in ac_difference]

In [75]:
res

[0.00022119000221187957, 0.0, 0.0006635700066356387, 0.0006635700066356387]

Answer: The smallest difference is the difference between the original accuracy and the accuracy without *balance* = 0.0

# Question 6
* Now let's train a regularized logistic regression.
* Let's try the following values of the parameter C: [0, 0.01, 0.1, 1, 10].
* Train models using all the features as in Q4.
* Calculate the accuracy on the validation dataset and round it to 3 decimal digits.

Which of these C leads to the best accuracy on the validation set?
* 0.01, 0.1, 1, 10, 100?

Note: If there are multiple options, select the smallest C.

In [77]:
dv = DictVectorizer(sparse=False)

train_dict = df_train[categorical + numerical].to_dict(orient='records')
X_train = dv.fit_transform(train_dict)

val_dict = df_val[categorical + numerical].to_dict(orient='records')
X_val = dv.transform(val_dict)    

In [78]:
ac_6 = []
for c in [0.01, 0.1, 1, 10, 100]:
    # if c=0 then InvalidParameterError: The 'C' parameter of LogisticRegression must be a float 
    # in the range (0.0, inf]. Got 0 instead.
    model = LogisticRegression(solver='liblinear', C=c, max_iter=1000, random_state=42)
    model.fit(X_train, y_train)

    y_pred = model.predict_proba(X_val)[:, 1]
    y_decision = (y_pred >= 0.5)
    accuracy_score = (y_val == y_decision).mean()
    print("For c={} ".format(c, round(accuracy_score, 3)))
    ac_6.append(accuracy_score)

0.01 0.899
0.1 0.9
1 0.901
10 0.901
100 0.901


In [298]:
ac_6

[0.8986949789869498,
 0.9002433090024331,
 0.9007962840079629,
 0.9012386640123866,
 0.9013492590134926]

In [299]:
max(ac_6)

0.9013492590134926

Answer: either 100 (measured before round()) or 1 (the smallest out of equal three after round())!